dist: xenial
language: java
jdk:
  - openjdk8
addons:
  apt:
    packages:
      - junit4
      - ant
script: ant -Dprotobuf.uptodate=true test checkstyle
notifications:
  email:
    recipients:
      - hridesh@iastate.edu
      - rdyer@bgsu.edu
    on_success: change
    on_failure: always
